### ISSUE TITLE
asMutable({deep:true}) doesn't work with date objects.

### ISSUE THREAD

**Issue by jjulicher** [rtfeldman/seamless-immutable#45]
var test = Immutable({mydate: new Date()})
test.asMutable({deep:true});

result:

Uncaught TypeError: obj.asMutable is not a function
    at asDeepMutable (http://localhost:8080/resource-bundles/bowerComponents.resource/seamless-immutable/seamless-immutable.js:215:20)
    at Object.asMutableObject (http://localhost:8080/resource-bundles/bowerComponents.resource/seamless-immutable/seamless-immutable.js:304:31)
    at Object.eval (eval at evaluate (unknown source), <anonymous>:1:6)
    at Object.InjectedScript._evaluateOn (<anonymous>:895:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:954:21)

**Comment by scriptguru** [comment]
Why would it work with date objects?
I thought it was supposed to work only with data that can be serialized to JSON and deserialized from JSON natively.

Still it's possible to store date as a timestamp to workaround this.
